DIRS := \
	arch/$(ARCH)/	\
	base/		\
	ctype/		\
	db-files/	\
	dirent/		\
	ipc/		\
	locale/		\
	malloc/		\
	net/		\
	posix-misc/	\
	signal/		\
	stdio/		\
	stdlib/		\
	string/		\
	syscalls/	\
	termios/	\
	time/		\
	unistd/		\
	util-bsd/	\

LIBNAME := libc
export LIBNAME
