SRC = 	\
	_sys_siglist	\
	bsd_signal	\
	sigaddset	\
	sigdelset	\
	sigemptyset	\
	sigfillset	\
	sighold		\
	sigignore	\
	siginterrupt	\
	sigismember	\
	siglongjmp	\
	signal		\
	sigpause	\
	sigrelse	\
	sigset		\
	sigwaitinfo	\
	strsignal	\
