struct stat {
	dev_t		st_dev;
	ino_t		st_ino;
	mode_t		st_mode;
	nlink_t		st_nlink;
	uid_t		st_uid;
	gid_t		st_gid;
	dev_t		st_rdev;
	off_t		st_size;
	blksize_t	st_blksize;
	blkcnt_t	st_blocks;
	time_t		st_atime;
	time_t		st_atime_nsec;
	time_t		st_mtime;
	time_t		st_mtime_nsec;
	time_t		st_ctime;
	time_t		st_ctime_nsec;
	unsigned long	__unused4;
	unsigned long	__unused5;
};
