TODO=	\
	strftime	\

SRC = 	\
	__time2tm	\
	__tm2time	\
	adjtime		\
	asctime		\
	asctime_r	\
	ctime		\
	ctime_r		\
	difftime	\
	ftime		\
	gmtime		\
	gmtime_r	\
	localtime	\
	localtime_r	\
	mktime		\
	ntp_gettime	\
	strftime	\
