#ifndef _SYS_POSIX_CONF_H
#define _SYS_POSIX_CONF_H

#define _POSIX_CHOWN_RESTRICTED			1
#define _POSIX_JOB_CONTROL			1
#define _POSIX_NO_TRUNC				1
#define _POSIX_REGEXP				1
#define _POSIX_SAVED_IDS			1
#define _POSIX_SHELL				1
#define _POSIX_VDISABLE				1
#define _POSIX_VERSION				200112L

#define _POSIX2_C_BIND				200112L

// names for (f)pathconf()
#define _PC_ALLOC_SIZE_MIN			0
#define _PC_ASYNC_IO				1
#define _PC_CHOWN_RESTRICTED			2
#define _PC_FILESIZEBITS			3
#define _PC_LINK_MAX				4
#define _PC_MAX_CANON				5
#define _PC_MAX_INPUT				6
#define _PC_NAME_MAX				7
#define _PC_NO_TRUNC				8
#define _PC_PATH_MAX				9
#define _PC_PIPE_BUF				10
#define _PC_PRIO_IO				11
#define _PC_REC_INCR_XFER_SIZE			12
#define _PC_REC_MAX_XFER_SIZE			13
#define _PC_REC_MIN_XFER_SIZE			14
#define _PC_REC_XFER_ALIGN			15
#define _PC_SYMLINK_MAX				16
#define _PC_SYNC_IO				17
#define _PC_VDISABLE				18

// names for confstr()
#define _CS_PATH				0

#if 0
// names for sysconf()
#define _SC_2_C_BIND				0
#define _SC_2_C_DEV				1
#define _SC_2_C_VERSION				2
#define _SC_2_CHAR_TERM				3
#define _SC_2_FORT_DEV				4
#define _SC_2_FORT_RUN				5
#define _SC_2_LOCALEDEF				6
#define _SC_2_PBS				7
#define _SC_2_PBS_ACCOUNTING			8
#define _SC_2_PBS_CHECKPOINT			9
#define _SC_2_PBS_LOCATE			10
#define _SC_2_PBS_MESSAGE			11
#define _SC_2_PBS_TRACK				12
#define _SC_2_SW_DEV				13
#define _SC_2_UPE				14
#define _SC_2_VERSION				15
#define _SC_ADVISORY_INFO			16
#define _SC_ARG_MAX				17
#define _SC_AIO_LISTIO_MAX			18
#define _SC_AIO_MAX				19
#define _SC_AIO_PRIO_DELTA_MAX			20
#define _SC_ASYNCHRONOUS_IO			21
#define _SC_ATEXIT_MAX				22
#define _SC_BARRIERS				23
#define _SC_BC_BASE_MAX				24
#define _SC_BC_DIM_MAX				25
#define _SC_BC_SCALE_MAX			26
#define _SC_BC_STRING_MAX			27
#define _SC_CHILD_MAX				28
#define _SC_CLK_TCK				29
#define _SC_CLOCK_SELECTION			30
#define _SC_COLL_WEIGHTS_MAX			31
#define _SC_CPUTIME				32
#define _SC_DELAYTIMER_MAX			33
#define _SC_EXPR_NEST_MAX			34
#define _SC_FILE_LOCKING			35
#define _SC_FSYNC				36
#define _SC_GETGR_R_SIZE_MAX			37
#define _SC_GETPW_R_SIZE_MAX			38
#define _SC_HOST_NAME_MAX			39
#define _SC_IOV_MAX				40
#define _SC_IPV6				41
#define _SC_JOB_CONTROL				42
#define _SC_LINE_MAX				43
#define _SC_LOGIN_NAME_MAX			44
#define _SC_MAPPED_FILES			45
#define _SC_MEMLOCK				46
#define _SC_MEMLOCK_RANGE			47
#define _SC_MEMORY_PROTECTION			48
#define _SC_MESSAGE_PASSING			49
#define _SC_MONOTONIC_CLOCK			50
#define _SC_MQ_OPEN_MAX				51
#define _SC_MQ_PRIO_MAX				52
#define _SC_NGROUPS_MAX				53
#define _SC_OPEN_MAX				54
#define _SC_PAGE_SIZE				55
#define _SC_PAGESIZE				56
#define _SC_PRIORITIZED_IO			57
#define _SC_PRIORITY_SCHEDULING			58
#define _SC_RAW_SOCKETS				59
#define _SC_RE_DUP_MAX				60
#define _SC_READER_WRITER_LOCKS			61
#define _SC_REALTIME_SIGNALS			62
#define _SC_REGEXP				63
#define _SC_RTSIG_MAX				64
#define _SC_SAVED_IDS				65
#define _SC_SEMAPHORES				66
#define _SC_SEM_NSEMS_MAX			67
#define _SC_SEM_VALUE_MAX			68
#define _SC_SHARED_MEMORY_OBJECTS		69
#define _SC_SHELL				70
#define _SC_SIGQUEUE_MAX			71
#define _SC_SPAWN				72
#define _SC_SPIN_LOCKS				73
#define _SC_SPORADIC_SERVER			74
#define _SC_STREAM_MAX				75
#define _SC_SYMLOOP_MAX				76
#define _SC_SYNCHRONIZED_IO			77
#define _SC_STREAMS				78
#define _SC_THREAD_ATTR_STACKADDR		79
#define _SC_THREAD_ATTR_STACKSIZE		80
#define _SC_THREAD_CPUTIME			81
#define _SC_THREAD_DESTRUCTOR_ITERATIONS	82
#define _SC_THREAD_KEYS_MAX			83
#define _SC_THREAD_PRIO_INHERIT			84
#define _SC_THREAD_PRIO_PROTECT			85
#define _SC_THREAD_PRIORITY_SCHEDULING		86
#define _SC_THREAD_PROCESS_SHARED		87
#define _SC_THREAD_SAFE_FUNCTIONS		88
#define _SC_THREAD_SPORADIC_SERVER		89
#define _SC_THREAD_STACK_MIN			90
#define _SC_THREAD_THREADS_MAX			91
#define _SC_TIMEOUTS				92
#define _SC_THREADS				93
#define _SC_TIMER_MAX				94
#define _SC_TIMERS				95
#define _SC_TRACE				96
#define _SC_TRACE_EVENT_FILTER			97
#define _SC_TRACE_INHERIT			98
#define _SC_TRACE_LOG				99
#define _SC_TTY_NAME_MAX			100
#define _SC_TYPED_MEMORY_OBJECTS		101
#define _SC_TZNAME_MAX				102
#define _SC_V6_ILP32_OFF32			103
#define _SC_V6_ILP32_OFFBIG			104
#define _SC_V6_LP64_OFF64			105
#define _SC_V6_LPBIG_OFFBIG			106
#define _SC_VERSION				107
#define _SC_XOPEN_CRYPT				108
#define _SC_XOPEN_ENH_I18N			109
#define _SC_XOPEN_LEGACY			110
#define _SC_XOPEN_REALTIME			111
#define _SC_XOPEN_REALTIME_THREADS		112
#define _SC_XOPEN_SHM				113
#define _SC_XOPEN_STREAMS			114
#define _SC_XOPEN_UNIX				115
#define _SC_XOPEN_VERSION			116
#define _SC_XOPEN_XCU_VERSION			117
#endif

#endif
